overrides:
  esbuild: ^0.28.2

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoreWorkspaceRootCheck: true

minimumReleaseAge: 0

pmOnFail: warn
shamefullyHoist: true

strictPeerDependencies: false
