catalog:
  '@ffmpeg/ffmpeg': ^0.12.15
  '@ffmpeg/types': ^0.12.4
  '@ffmpeg/util': ^0.12.2
  '@huggingface/transformers': ^3.3.3
  '@shikijs/core': ^3.1.0
  '@shikijs/engine-javascript': ^3.1.0
  '@shikijs/langs': ^3.1.0
  '@shikijs/themes': ^3.1.0
  '@tiptap/starter-kit': ^2.11.5
  '@tiptap/vue-3': ^2.11.5
  '@unocss/reset': ^66.0.0
  '@webcontainer/api': 1.5.1-internal.9
  dayjs: ^1.11.13
  file-saver: ^2.0.5
  floating-vue: ^5.2.2
  jszip: ^3.10.1
  lightningcss-wasm: ^1.29.1
  matter-attractors: ^0.1.6
  matter-js: ^0.20.0
  moveable: ^0.53.0
  oxidase: ^0.0.3
  p5i: ^0.6.0
  plain-shiki: ^0.1.1
  simplex-noise: ^4.0.3
  ts-blank-space: ^0.6.0
  ufo: ^1.5.4
  zrender: ^5.6.1

packages:
  - .
